const sequelize = require('./models');
const Artist = require('./models/artist');
const Album = require('./models/album');
const Playlist = require('./models/playlist');

const seedDatabase = async () => {
    await sequelize.sync({ force: true });

    const artists = await Artist.bulkCreate([
        { name: 'The Beatles' },
        { name: 'Elvis Presley' },
        { name: 'Michael Jackson' },
        { name: 'Madonna' },
        { name: 'Elton John' },
        { name: 'Led Zeppelin' },
        { name: 'Pink Floyd' },
        { name: 'Rihanna' },
        { name: 'Eminem' },
        { name: 'Taylor Swift' },
        { name: 'Beyoncé' },
        { name: 'Bruno Mars' },
        { name: 'Adele' },
        { name: 'Drake' },
        { name: 'Kanye West' },
        { name: 'Justin Bieber' },
        { name: 'Ed Sheeran' },
        { name: 'Ariana Grande' },
        { name: 'Lady Gaga' },
        { name: 'Katy Perry' },
        { name: 'Shakira' },
        { name: 'Coldplay' },
        { name: 'Maroon 5' },
        { name: 'Imagine Dragons' },
        { name: 'One Direction' },
        { name: 'The Rolling Stones' },
        { name: 'Queen' },
        { name: 'U2' },
        { name: 'Nirvana' },
        { name: 'Linkin Park' },
        { name: 'Green Day' },
        { name: 'Red Hot Chili Peppers' },
        { name: 'Foo Fighters' },
        { name: 'The Weeknd' },
        { name: 'Billie Eilish' },
        { name: 'Post Malone' },
        { name: 'Harry Styles' },
        { name: 'Dua Lipa' },
        { name: 'Shawn Mendes' },
        { name: 'Selena Gomez' },
        { name: 'Camila Cabello' },
        { name: 'Cardi B' },
        { name: 'Miley Cyrus' },
        { name: 'Sam Smith' },
        { name: 'Halsey' },
        { name: 'Lizzo' },
        { name: 'Doja Cat' },
        { name: 'Lil Nas X' },
        { name: 'Travis Scott' },
        { name: 'J Balvin' }
    ]);

    const albums = await Album.bulkCreate([
        { title: 'Abbey Road', artistId: artists[0].id },
        { title: 'Elvis Presley', artistId: artists[1].id },
        { title: 'Thriller', artistId: artists[2].id },
        { title: 'Like a Virgin', artistId: artists[3].id },
        { title: 'Goodbye Yellow Brick Road', artistId: artists[4].id },
        { title: 'Led Zeppelin IV', artistId: artists[5].id },
        { title: 'The Dark Side of the Moon', artistId: artists[6].id },
        { title: 'Anti', artistId: artists[7].id },
        { title: 'The Marshall Mathers LP', artistId: artists[8].id },
        { title: '1989', artistId: artists[9].id },
        { title: 'Lemonade', artistId: artists[10].id },
        { title: '24K Magic', artistId: artists[11].id },
        { title: '21', artistId: artists[12].id },
        { title: 'Scorpion', artistId: artists[13].id },
        { title: 'The College Dropout', artistId: artists[14].id },
        { title: 'Purpose', artistId: artists[15].id },
        { title: 'Divide', artistId: artists[16].id },
        { title: 'Sweetener', artistId: artists[17].id },
        { title: 'The Fame', artistId: artists[18].id },
        { title: 'Teenage Dream', artistId: artists[19].id },
        { title: 'Laundry Service', artistId: artists[20].id },
        { title: 'A Rush of Blood to the Head', artistId: artists[21].id },
        { title: 'Songs About Jane', artistId: artists[22].id },
        { title: 'Evolve', artistId: artists[23].id },
        { title: 'Up All Night', artistId: artists[24].id },
        { title: 'Sticky Fingers', artistId: artists[25].id },
        { title: 'A Night at the Opera', artistId: artists[26].id },
        { title: 'The Joshua Tree', artistId: artists[27].id },
        { title: 'Nevermind', artistId: artists[28].id },
        { title: 'Hybrid Theory', artistId: artists[29].id },
        { title: 'American Idiot', artistId: artists[30].id },
        { title: 'Californication', artistId: artists[31].id },
        { title: 'Wasting Light', artistId: artists[32].id },
        { title: 'After Hours', artistId: artists[33].id },
        { title: 'When We All Fall Asleep, Where Do We Go?', artistId: artists[34].id },
        { title: 'Hollywood\'s Bleeding', artistId: artists[35].id },
        { title: 'Fine Line', artistId: artists[36].id },
        { title: 'Future Nostalgia', artistId: artists[37].id },
        { title: 'Shawn Mendes', artistId: artists[38].id },
        { title: 'Rare', artistId: artists[39].id },
        { title: 'Romance', artistId: artists[40].id },
        { title: 'Invasion of Privacy', artistId: artists[41].id },
        { title: 'Plastic Hearts', artistId: artists[42].id },
        { title: 'In the Lonely Hour', artistId: artists[43].id },
        { title: 'Manic', artistId: artists[44].id },
        { title: 'Cuz I Love You', artistId: artists[45].id },
        { title: 'Hot Pink', artistId: artists[46].id },
        { title: 'Montero', artistId: artists[47].id },
        { title: 'Astroworld', artistId: artists[48].id },
        { title: 'Vibras', artistId: artists[49].id }
    ]);

    const playlists = await Playlist.bulkCreate([
        { name: 'Top Hits' },
        { name: 'Rock Classics' },
        { name: 'Pop Essentials' },
        { name: 'Hip-Hop Hits' },
        { name: 'Country Favorites' },
        { name: 'Jazz Vibes' },
        { name: 'Classical Masterpieces' },
        { name: 'Indie Mix' },
        { name: 'Electronic Beats' },
        { name: 'Reggae Rhythms' },
        { name: 'Latin Grooves' },
        { name: 'Blues Legends' },
        { name: 'Soul Classics' },
        { name: 'R&B Hits' },
        { name: 'Folk Favorites' },
        { name: 'Metal Mayhem' },
        { name: 'Punk Rock' },
        { name: 'Alternative Anthems' },
        { name: 'Dance Party' },
        { name: 'Workout Mix' },
        { name: 'Chill Vibes' },
        { name: 'Acoustic Sessions' },
        { name: 'Love Songs' },
        { name: 'Throwback Hits' },
        { name: 'Holiday Tunes' },
        { name: 'Kids Party' },
        { name: 'Road Trip' },
        { name: 'Study Beats' },
        { name: 'Sleep Sounds' },
        { name: 'Morning Motivation' },
        { name: 'Evening Relaxation' },
        { name: 'Dinner Party' },
        { name: 'Summer Hits' },
        { name: 'Winter Warmers' },
        { name: 'Spring Fling' },
        { name: 'Autumn Acoustics' },
        { name: 'Festival Favorites' },
        { name: 'Live Performances' },
        { name: 'Cover Songs' },
        { name: 'Duets' },
        { name: 'One-Hit Wonders' },
        { name: '90s Nostalgia' },
        { name: '80s Classics' },
        { name: '70s Hits' },
        { name: '60s Gold' },
        { name: '50s Rock\'n\'Roll' },
        { name: '40s Swing' },
        { name: '30s Jazz' },
        { name: '20s Blues' },
        { name: '10s Pop' }
    ]);

    console.log('Database seeded!');
};

seedDatabase().catch(err => {
    console.error('Failed to seed database:', err);
});